# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

orbs:
  node: circleci/node@4.1

jobs:
  test:
    docker:
      - image: circleci/node:13-browsers

    steps:
      - checkout
      - run: yarn
      - run: yarn test

workflows:
  sample:
    jobs:
      - test:
          version: "16.0"
          filters:
            branches:
              ignore: main
